### ISSUE TITLE
Strange evaluation with "one plus one"

### ISSUE THREAD

**Issue by Tpt** [s-i-newton/calchas#1]
It returns "one" and is not filtered by isMath or isInteresting https://askplatyp.us/?lang=fr&q=one%20plus%20one

Same problem with "two plus three"

**Comment by marc-chevalier** [comment]
isMath returns 1 meaning it's not sure its math or not. I will adapt isMath to return 2 (surely is math) more precisely and I think we should process as math only when isMath returns 2.

**Comment by marc-chevalier** [comment]
I think 570ebeb should make you happy.

**Comment by Tpt** [comment]
Thank you!

**Comment by marc-chevalier** [comment]
By the way, I made isMath to returns an enum, it's more clear than 0, 1, 2.
